version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-jasper
    versions:
    - 10.0.2
    - 10.0.4
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-core
    versions:
    - 10.0.2
    - 10.0.4
  - dependency-name: org.webjars:bootstrap
    versions:
    - 4.6.0
  - dependency-name: org.springframework:spring-webmvc
    versions:
    - 5.3.4
  - dependency-name: org.springframework:spring-web
    versions:
    - 5.3.4
  - dependency-name: org.springframework:spring-context
    versions:
    - 5.3.4
