CREATE TABLE IF NOT EXISTS author
(
    id   INT NOT NULL AUTO_INCREMENT,
    text VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS author
(
    id   INT NOT NULL AUTO_INCREMENT,
    name VARCHAR NOT NULL
);
